language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer install
  - mysql -e -uroot "CREATE USER 'test'@'localhost' IDENTIFIED BY 'test';"
  - mysql -e -uroot "GRANT USAGE ON *.* TO 'test'@'localhost' IDENTIFIED BY 'test' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;"
  - mysql -e -uroot "CREATE DATABASE IF NOT EXISTS test;"
  - mysql -e -uroot "GRANT ALL PRIVILEGES ON test.* TO 'test'@'localhost';"
